services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-quiz}
      - POSTGRES_USER=${POSTGRES_USER:-quiz}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-quiz}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data: