apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: quiz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: ghcr.io/your-org/quiz-api-gateway:latest
          ports:
            - containerPort: 3000
          env:
            - name: API_GATEWAY_PORT
              value: "3000"
            - name: AUTH_JWT_SECRET
              value: changeme-dev-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
